---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp:
  labels:
    app: nginx
  name: nginx
  annotations:
    flux.weave.works/automated: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.16-alpine-perl
        name: nginx
        resources: {}
status: {}
